# El entorno de trabajo

Este es el entorno de trabajo que vamos a utilizar en las sesiones prácticas de la asignatura, se llama Jupyter y viene incluido en la distribución *Anaconda* de *Python*.

En este entorno podemos combinar 'cajas' de texto en las que explicar ideas y conceptos, y 'cajas' de código en las que definir o evaluar funciones *Python*.

In [2]:
1+2

3

El tipo de caja se controla con el menú desplegable de la derecha en el que podemos escoger 'Code' para cajas de código o 'Markdown' para cajas de texto.

El texto se escribe en formato 'Markdown' con el que podemos fácilmente crear cabeceras, destacar texto, crear listas, incluir imágenes o enlaces a páginas web. Un resumen de las directivas 'Markdown' se puede encontrar fácilmente en internet buscando 'markdown cheat sheet'.

Una vez completado el contenido de una caja, podemos evaluarla con la combinación de teclas Control-Enter (quedándonos en la misma caja que hemos evaluado), Mayusculas-Enter (pasando a la siguiente caja) o Alt-Enter (creando una nueva caja).

También disponemos de las habituales opciones de edición en las cajas (cortar, copiar, pegar) así como otras que nos permiten dividir una caja o unir cajas. En el menú superior tenemos acceso a estas y otras opciones.

En el menú 'Help' disponéis de enlaces a documentación de algunas de las herramientas que usaremos durante el curso, *Python*, *NumPy*, *SciPy*, *Matplotlib*, *Pandas*

## Introducción a NumPy

*NumPy* es una biblioteca para manejo de arrays multidimensionales, cuyas componentes son datos del mismo tipo.

In [3]:
import numpy as np

Para crear un array *NumPy* usamos la función `np.array`, proporcionando los datos como listas de listas, con la misma cantidad de datos.

In [4]:
a = np.array([[1.8,2.3,3.4],
              [2.5,3.2,1.1]])

El atributo `ndim` nos indica el número de dimensiones del array y el atributo `shape` el número de datos que hay en cada dimensión

In [5]:
a.ndim

2

In [6]:
a.shape

(2, 3)

Para obtener un dato debemos indicar su posición (contada desde 0) como una secuencia de valores que indican la componente en la que se encuentra

In [7]:
a[1,1]

3.2

Los datos de un array se pueden reorganizar cambiando las dimensiones con el método (no destructivo) `np.reshape`

In [8]:
a.reshape(3,2)

array([[1.8, 2.3],
       [3.4, 2.5],
       [3.2, 1.1]])

In [9]:
a

array([[1.8, 2.3, 3.4],
       [2.5, 3.2, 1.1]])

In [10]:
np.random.random((3,4))

array([[0.81181951, 0.44774862, 0.29356943, 0.4244363 ],
       [0.69270119, 0.25800078, 0.16866725, 0.62956619],
       [0.08330119, 0.3945267 , 0.35009807, 0.50892812]])

In [11]:
np.arange(1,12,2).reshape(2,3)

array([[ 1,  3,  5],
       [ 7,  9, 11]])

### Operaciones con arrays

In [12]:
A = np.array([[1,2,3],[4,5,6]])
B = np.random.random((2,3))

In [13]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
B

array([[0.61810574, 0.67298116, 0.16364724],
       [0.10096573, 0.13288475, 0.79953038]])

In [15]:
A *= 3

In [16]:
A

array([[ 3,  6,  9],
       [12, 15, 18]])

In [17]:
A+B

array([[ 3.61810574,  6.67298116,  9.16364724],
       [12.10096573, 15.13288475, 18.79953038]])

In [18]:
A*B

array([[ 1.85431722,  4.03788694,  1.47282519],
       [ 1.2115888 ,  1.99327118, 14.39154692]])

In [19]:
A.min()

3

In [20]:
B.max()

0.799530384227215

In [21]:
B>0.5

array([[ True,  True, False],
       [False, False,  True]])

In [22]:
B.T

array([[0.61810574, 0.10096573],
       [0.67298116, 0.13288475],
       [0.16364724, 0.79953038]])

In [23]:
np.dot(A,B.T)

array([[ 7.36502935,  8.29597913],
       [20.4576366 , 17.5964069 ]])

### Indexado y slicing

In [24]:
C = np.arange(15).reshape((3,5))

In [25]:
C

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [26]:
C[:,:3:2]

array([[ 0,  2],
       [ 5,  7],
       [10, 12]])

In [28]:
C[-1]

array([10, 11, 12, 13, 14])

In [29]:
C[:-1]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
C[:,2]

array([ 2,  7, 12])

### Indexación con arrays

In [31]:
D = np.arange(15)**2

In [32]:
D

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196], dtype=int32)

In [33]:
i = np.array([2,3,0,6])

In [34]:
D[i]

array([ 4,  9,  0, 36], dtype=int32)

In [35]:
j = np.array([[6,1,9],[4,2,4],[3,7,1]])

In [36]:
D[j]

array([[36,  1, 81],
       [16,  4, 16],
       [ 9, 49,  1]], dtype=int32)

### Indexación booleana

In [37]:
E = np.random.random((2,4))

In [38]:
E

array([[0.69871755, 0.38792069, 0.81570716, 0.05441244],
       [0.91833836, 0.10648101, 0.65885538, 0.82389211]])

In [42]:
I = E>0.5

In [43]:
I

array([[ True, False,  True, False],
       [ True, False,  True,  True]])

In [44]:
E[I]

array([0.69871755, 0.81570716, 0.91833836, 0.65885538, 0.82389211])

In [45]:
E[I] = 0

In [46]:
E

array([[0.        , 0.38792069, 0.        , 0.05441244],
       [0.        , 0.10648101, 0.        , 0.        ]])

In [47]:
E[E!=0]

array([0.38792069, 0.05441244, 0.10648101])

## Ejercicios

Generar una matrix aleatoria 3x4 y normalizar sus componentes (escalándolos) de manera que el menor sea 0 y el mayor 1.

In [56]:
Ej1 = np.random.random((3,4))

In [57]:
Ej1

array([[0.4739524 , 0.94368347, 0.46773295, 0.19814195],
       [0.46072574, 0.31452433, 0.20646518, 0.75552353],
       [0.52465006, 0.94957021, 0.49152388, 0.50936846]])

In [58]:
Ej1.min()

0.19814195034607762

In [59]:
Ej1.max()

0.949570209700384

In [61]:
(Ej1-Ej1.min())/(Ej1.max()-Ej1.min())

array([[0.36704828, 0.99216593, 0.35877144, 0.        ],
       [0.34944625, 0.15488156, 0.01107654, 0.74176287],
       [0.43451668, 1.        , 0.39043239, 0.41417994]])

In [64]:
def normalizaArray(a):
    return (a-a.min())/(a.max()-a.min())

In [65]:
normalizaArray(Ej1)

array([[0.36704828, 0.99216593, 0.35877144, 0.        ],
       [0.34944625, 0.15488156, 0.01107654, 0.74176287],
       [0.43451668, 1.        , 0.39043239, 0.41417994]])

En una matriz 20x20, obtener la matriz que se obtiene al extraer las
filas de índice par y las columnas de índice impar 

In [66]:
Ej2 = np.arange(0,400,1).reshape((20,20))

In [67]:
Ej2

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 1

In [69]:
Ej2[1::2,::2]

array([[ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 60,  62,  64,  66,  68,  70,  72,  74,  76,  78],
       [100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [180, 182, 184, 186, 188, 190, 192, 194, 196, 198],
       [220, 222, 224, 226, 228, 230, 232, 234, 236, 238],
       [260, 262, 264, 266, 268, 270, 272, 274, 276, 278],
       [300, 302, 304, 306, 308, 310, 312, 314, 316, 318],
       [340, 342, 344, 346, 348, 350, 352, 354, 356, 358],
       [380, 382, 384, 386, 388, 390, 392, 394, 396, 398]])

In [70]:
def reduceArray(a):
    return a[1::2,::2]

In [71]:
reduceArray(Ej2)

array([[ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 60,  62,  64,  66,  68,  70,  72,  74,  76,  78],
       [100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [180, 182, 184, 186, 188, 190, 192, 194, 196, 198],
       [220, 222, 224, 226, 228, 230, 232, 234, 236, 238],
       [260, 262, 264, 266, 268, 270, 272, 274, 276, 278],
       [300, 302, 304, 306, 308, 310, 312, 314, 316, 318],
       [340, 342, 344, 346, 348, 350, 352, 354, 356, 358],
       [380, 382, 384, 386, 388, 390, 392, 394, 396, 398]])

Dada una matriz A de tamaño 20x10 y otra B de tamaño 20x1 con valores entre
0 y 100, devolver una matriz conteniendo las filas de A que corresponden a las
posiciones de B que son mayores de 50 

In [73]:
Ej3A = np.dot(np.arange(0,20,1).reshape(20,1),
              np.ones(10).reshape(1,10))

In [74]:
Ej3A

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [11., 11., 11., 11., 11., 11., 11., 11., 11., 11.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [15., 15., 15., 15., 15., 15., 15., 15., 15., 15.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16., 16.

In [75]:
Ej3B = np.random.permutation(100)[:20]

In [76]:
Ej3B

array([93, 78,  2,  6, 64, 68,  0, 34,  8, 74, 14, 43, 89, 77, 71, 82, 73,
       40,  5, 15])

In [77]:
Ej3B > 50

array([ True,  True, False, False,  True,  True, False, False, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False])

In [78]:
Ej3A[Ej3B > 50]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [15., 15., 15., 15., 15., 15., 15., 15., 15., 15.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16., 16.]])

In [79]:
def seleccionaFilas(a,b):
    return a[b > 50]

In [80]:
seleccionaFilas(Ej3A,Ej3B)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [15., 15., 15., 15., 15., 15., 15., 15., 15., 15.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16., 16.]])